version: '3'

volumes:
  grafana-storage: 


services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
     - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - 4000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  
  prometheus_exporter:
    build: ./prometheus_exporter    
    ports:
      - 9394:9394